### ISSUE TITLE
Complex values are supported only in config file but not on CLI

### ISSUE THREAD

**Issue by den-is** [den-is/ktempl#1]
For now, ktempl supports complex values declaration only via config file provided via `-c`, `--config`, `config.yaml` in the same dir with ktempl or `/etc/ktempl/config.yaml` 

Complex values are:

```yaml
# maps
mymap:
  color: red
  active: true

# lists
mylist:
- one
- two
- 3
```

It should be allowed to pass complex values using `--set` and dot-notation like it is done in [helm](https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing)

Probably for that to work it will be required to review each user-passed `--set` argument.
Then try and parse it into `map[string]interface{}` and then merge into values from the config file
